global:
  namespace: dev

kafka-ui:
  envs:
    config:
      SERVER_SERVLET_CONTEXT_PATH: ""
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-umbrella:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "kafka-umbrella-zookeeper:2181"

kafka-producer:
  replicas: 1
  image:
    repository: jacobamar1/kafka-producer
    tag: 0.1

kafka-consumer:
  replicas: 1
  image:
    repository: jacobamar1/kafka-consumer
    tag: 0.1